# Generated by Django 5.0.1 on 2024-01-04 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=datetime.date(2024, 1, 4)),
        ),
    ]
